<?php
/**
 * @file
 * Code for the Quilted Media feature.
 */

include_once 'quilted_responsive.features.inc';


/**
 * Implements hook_wysiwyg_editor_settings_alter().
 *
 * Added to make WYSIWYG compatible with ckeditor 4.x. See #1956778.
 */
function quilted_responsive_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
    $settings['allowedContent'] = TRUE;
  }
}
